sb-admin-2.Web/Models/DTO/RecordDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sb_admin_2.Web.Models.DTO
{
    public class RecordDTO
    {
        public int StudentId { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Sex { get; set; }
        public DateTime DOB { get; set; }
        public string Contact_number { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Age { get; set; }

    }
}

sb-admin-2.Web/Models/DTO/loginFormDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sb_admin_2.Web.Models.DTO
{
    public class loginFormDTO
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

sb-admin-2.Web/Models/Navbar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sb_admin_2.Web.Models
{
    public class Navbar
    {
        public int Id { get; set; }
        public string nameOption { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string area { get; set; }
        public string imageClass { get; set; }
        public string activeli { get; set; }
        public bool status { get; set; }
        public int parentId { get; set; }
        public bool isParent { get; set; }
    }
}

sb-admin-2.Web/Models/Repository/DataTableRepository.cs
using sb_admin_2.Web.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sb_admin_2.Web.Models.Repository
{
    public class DataTableRepository
    {

        RegistrationEntities db = new RegistrationEntities();

        public List<RecordDTO> records(string category, string keyword)
        {

            List<RecordDTO> records = new List<RecordDTO>();
            List<Member> members = new List<Member>();

            if (!string.IsNullOrEmpty(category))
            {
                if (category == "First Name")
                {
                    members = db.Members.Where(a => a.Firstname.Contains(keyword)).ToList();
                }
                else if (category == "Last Name")
                {
                    members = db.Members.Where(a => a.Lastname.Contains(keyword)).ToList();
                }
                else if (category == "Email")
                {
                    members = db.Members.Where(a => a.Email.Contains(keyword)).ToList();
                }

            }
            else
            {
                members = db.Members.ToList();
            }


            //looping of details
            foreach (Member mem in members)
            {
                RecordDTO r = new RecordDTO();

                r.StudentId = mem.StudentId;
                r.Firstname = mem.Firstname;
                r.Lastname = mem.Lastname;
                r.Email = mem.Email;
                r.Address = mem.Address;
                r.Email = mem.Email;

                records.Add(r);
            }


            return records;
        }






        public List<RecordDTO> Records1()
        {

            List<RecordDTO> records = new List<RecordDTO>();
            List<Member> members = db.Members.ToList();



            //looping of details
            foreach (Member member in members)
            {
                RecordDTO r = new RecordDTO();

                r.StudentId = member.StudentId;
                r.Firstname = member.Firstname;
                r.Lastname = member.Lastname;
                r.Email = member.Email;
                r.Address = member.Address;
                r.Email = member.Email;



                records.Add(r);
            }


            return records;
        }

    }
}

sb-admin-2.Web/Controllers/HomeController.cs
using sb_admin_2.Web.Models.DTO;
using sb_admin_2.Web.Models.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sb_admin_2.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MissionandVission()
        {
            return View();
        }

        public ActionResult CoreValues()
        {
            return View();
        }

        public ActionResult UniversityCalendar()
        {
            return View();
        }

        public ActionResult UniversityHymn()
        {
            return View();
        }

        public ActionResult SanBartolome()
        {
            return View();
        }

        public ActionResult Batasan()
        {
            return View();
        }

        public ActionResult SanFrancisco()
        {
            return View();
        }

        public ActionResult TranscriptOfRecord()
        {
            return View();
        }

        public ActionResult DownloadableForms()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }


        public JsonResult GetEvents()
        {
            using (RegistrationEntities dc = new RegistrationEntities())
            {
                var events = dc.Calendars.ToList();
                return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        [HttpPost]
        public JsonResult SaveEvent(Calendar e)
        {
            var status = false;
            using (RegistrationEntities dc = new RegistrationEntities())
            {
                if (e.EventID > 0)
                {
                    //Update the event
                    var v = dc.Calendars.Where(a => a.EventID == e.EventID).FirstOrDefault();
                    if (v != null)
                    {
                        v.Subject = e.Subject;
                        v.Start = e.Start;
                        v.End = e.End;
                        v.Description = e.Description;
                        v.IsFullDay = e.IsFullDay;
                        v.ThemeColor = e.ThemeColor;
                    }
                }
                else
                {
                    dc.Calendars.Add(e);
                }

                dc.SaveChanges();
                status = true;

            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public JsonResult DeleteEvent(int eventID)
        {
            var status = false;
            using (RegistrationEntities dc = new RegistrationEntities())
            {
                var v = dc.Calendars.Where(a => a.EventID == eventID).FirstOrDefault();
                if (v != null)
                {
                    dc.Calendars.Remove(v);
                    dc.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public JsonResult AjaxMethod()
        {
            RegistrationEntities entities = new RegistrationEntities();
            List<Member> members = (from account in entities.Members
                                      select account).ToList();
            return Json(members);
        }

        DataTableRepository dataTBrepository = new DataTableRepository();
        public ActionResult getRecords(string category, string keyword)
        {
            List<RecordDTO> records = dataTBrepository.records(category, keyword);
            return Json(new { data = records });
        }







    }
}

sb-admin-2.Web/Controllers/NavbarController.cs
using sb_admin_2.Web.Domain;
using sb_admin_2.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sb_admin_2.Web.Controllers
{
    public class NavbarController : Controller
    {
        // GET: Navbar
        public ActionResult Index()
        {
            var data = new Data();            
            return PartialView("_Navbar", data.navbarItems().ToList());
        }
    }
}

sb-admin-2.Web/Views/Home/Batasan.cshtml
@{
    ViewBag.Title = "Batasan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<<<<<<< Updated upstream
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
    </div>
    <div class="card-body">
        <div class="text-center">
            <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="img/undraw_posting_photo.svg" alt="">
        </div>
        <p>
            Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a
            constantly updated collection of beautiful svg images that you can use
            completely free and without attribution!
        </p>
        <a target="_blank" rel="nofollow" href="https://undraw.co/">
            Browse Illustrations on
            unDraw →
        </a>
    </div>
</div>

<div class="card text-white bg-success mb-3" style="max-width: 18rem;">
    <div class="card-header">Header</div>
    <div class="card-body">
        <h5 class="card-title">Success card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
=======
<div class="mapouter">
    <div class="gmap_canvas">
        <iframe width="500" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=qcu%20batasan&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://123movies-to-org.blogspot.com"></a><br>
        <style>
            .mapouter {
                position: relative;
                text-align: right;
                height: 996px;
                width: 988px;
            }
        </style><a href="https://google-map-generator.com"></a>
        <style>
            .gmap_canvas {
                overflow: hidden;
                background: none !important;
                height: 996px;
                width: 988px;
            }
        </style>
>>>>>>> Stashed changes
    </div>
</div>

sb-admin-2.Web/Views/Home/CoreValues.cshtml
@{
    ViewBag.Title = "CoreValues";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CoreValues</h2>

<div class="container-fluid">

    <!-- Page Heading -->
    
    <div class="row">

        <div class="col-lg-6">

            <!-- Core Values -->
            
                <div class="card-body">
                    <div class="custom-breadcrumns border-bottom">

                        <div class="container pt-4 mb-4">

                            <pre>
                                <p>
                                    E mbrace the
                                    

                                    N ew Normal with
                                    

                                    J ointness of Undertakings
                                    

                                    O rganizational Adaptability
                                    

                                    Y oke of efficiency and Effectiveness
                                </p>
                            </pre>


                        </div>
                    </div>
                </div>
            </div>
        </div>

sb-admin-2.Web/Views/Home/DownloadableForms.cshtml
@{
    ViewBag.Title = "DownloadableForms";
}

<h2>Downloadable Forms</h2>

sb-admin-2.Web/Views/Home/ForgotPassword.cshtml
@{
    ViewBag.Title = "ForgotPassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ForgetPassword</h2>

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                    <p class="mb-4">
                                        We get it, stuff happens. Just enter your email address below
                                        and we'll send you a link to reset your password!
                                    </p>
                                </div>
                                <form class="user">
                                    <div class="form-group">
                                        <input type="email" class="form-control form-control-user"
                                               id="exampleInputEmail" aria-describedby="emailHelp"
                                               placeholder="Enter Email Address...">
                                    </div>
                                    <a href="login.html" class="btn btn-primary btn-user btn-block">
                                        Reset Password
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="register.html">Create an Account!</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="login.html">Already have an account? Login!</a>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

sb-admin-2.Web/Views/Home/Index.cshtml
@{ ViewBag.Title = "Home Page";
    
}

<!--<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>-->
<!-- /.col-lg-12 -->
<!--</div>-->








<div>
    <div class="row">
        <div class="col-1">
            <button class="btn btn-primary" id="btnSearch"> SEARCH</button>
        </div>
        <div col="2">
            <select class="form-control" id="category">
                <option value=""></option>
                <option value="First Name">First Name</option>
                <option value="Last Name">Last Name</option>
                <option value="Email">Email</option>
            </select>
        </div>
        <div class="col-3">
            <input type="text" id="keyword" class="form-control" />
        </div>
    </div>
</div>
<br />
<table id="example">
</table>




<script>
    $("#btnSearch").click(function () {
    var _keyword = $("#keyword").val();
    var _category = $("#category").val();

    LoadDataTables(_category, _keyword);
});

function LoadDataTables(_category, _keyword) {
    $('#example').DataTable({
        paging: true,
        info: true,
        searching: true,
        info: true,
        destroy: true,
        lengthMenu: [[10, 20, 30, -1], [10, "All"]],
        ajax: {
            url: "../Home/getRecords",
            type: "POST",
            data: function (d) {
                d.category = _category;
                d.keyword = _keyword;

            }
        },
        columns: [
            { data: 'StudentId', title: "ID", visible: false },
            { data: 'Lastname', title: "First Name" },
            { data: 'Firstname', title: "Last Name" },
            { data: 'Email', title: "Email" },
            { data: 'Address', title: "Address" }

        ]
    });
}
</script>

sb-admin-2.Web/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                   id="exampleStudentNumber" aria-describedby="Help"
                                                   placeholder="Student Number...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                   id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">
                                                    Remember
                                                    Me
                                                </label>
                                            </div>
                                        </div>
                                        <a href="index.html" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </a>
                                        <hr>
                                        <a href="index.html" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Login with Google
                                        </a>

                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

sb-admin-2.Web/Views/Home/MissionandVission.cshtml
@{
    ViewBag.Title = "MissionandVission";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MissionandVission</h2>
<div class="card-body">
    <div class="custom-breadcrumn border-bottom">

        <div class="container pt-5 mb-5">


            <pre><p>MISSION</p>
            <left>
                <p>To provide a comprehensive education that enchances the lives of QCU students for nation building and as world citizen.</p>
        </div>
        </div>
    </div>

                <div class="card-body">
    <div class="custom-breadcrumn border-bottom">

        <div class="container pt-5 mb-5">

              <pre>  <left><p>VISION</p></left>
                <left><p> To be recognized as the #1 local University of employable graduates. </p></left>
                </pre>
        </div>
    </div>
</div>

sb-admin-2.Web/Views/Home/Register.cshtml
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register</h2>


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">

                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">

                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>

                            </div>
                            <form class="user">
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" id="exampleFirstName"
                                               placeholder="First Name">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control form-control-user" id="exampleLastName"
                                               placeholder="Last Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control form-control-user" id="exampleStudentNumber"
                                           placeholder="Student Number">
                                </div>

                                <div class="form-group">
                                    <input type="date" class="form-control form-control-user" id="exampleBirthday"
                                           placeholder="Birthday">

                                </div>

                                <div class="form-group">
                                    <select name="Campus" id="Ha" class="form-control form-control-user">
                                        <option value="sanbartolome">San Bartolome</option>
                                        <option value="sanfrancisco">San Francisco</option>
                                        <option value="batasan">Batasan</option>
                                    </select>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user"
                                               id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user"
                                               id="exampleConfirmPassword" placeholder="Confirm Password">
                                    </div>
                                </div>
                                <a href="login.html" class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </a>
                                <hr>
                                <a href="index.html" class="btn btn-google btn-user btn-block">
                                    <i class="fab fa-google fa-fw"></i> Register with Google
                                </a>

                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="forgot-password.html">Forgot Password?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="login.html">Already have an account? Login!</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <pre>
</pre>>


    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

sb-admin-2.Web/Views/Home/SanFrancisco.cshtml
@{
    ViewBag.Title = "SanFrancisco";
    Layout = "~/Views/Shared/_Student.cshtml";
}

<h2>SanFrancisco</h2>

<<<<<<< Updated upstream
=======
<div class="mapouter">
    <div class="gmap_canvas">
        <iframe width="500" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=qcu%20San%20Francisco&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://123movies-to-org.blogspot.com"></a><br>
        <style>
            .mapouter {
                position: relative;
                text-align: right;
                height: 996px;
                width: 988px;
            }
        </style><a href="https://google-map-generator.com"></a>
        <style>
            .gmap_canvas {
                overflow: hidden;
                background: none !important;
                height: 996px;
                width: 988px;
            }
        </style>
    </div>
</div>
>>>>>>> Stashed changes

sb-admin-2.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Bootstrap Admin Theme</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- DataTables CSS -->
    <link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <!-- DataTables Responsive CSS -->
    <link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/bower_components/morrisjs/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />

    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/bower_components/jquery/dist/jquery.min.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/bower_components/metisMenu/dist/metisMenu.min.js")"></script>

</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        @Html.Action("Index", "Navbar")
        
        <div id="page-wrapper">
            @RenderBody()          
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
         
    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/raphael/raphael-min.js")"></script>
 
    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")"></script>

    <!-- Custom Theme JavaScript -->
    <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>